apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-chart.fullname" . }}
  labels:
    {{- include "jitsi-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jitsi-chart.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-chart.fullname" . }}-jvb-udp
  labels:
    {{- include "jitsi-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.publicIp }}
  externalIPs:
  - {{ .Values.service.publicIp }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: 30300
      targetPort: 30300
      protocol: UDP
  selector:
    {{- include "jitsi-chart.selectorLabels" . | nindent 4 }}
